name: Continuous release

on:
  push:
    branches:
      - main

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Correct time
        run: |
          sudo timedatectl set-timezone America/Los_Angeles
          sudo timedatectl set-ntp true
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso mtools grub-pc-bin grub-common gcc-multilib
      
      - name: Configure
        run: ./configure
   
      - name: Build
        run: make
      
      - name: Upload IMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: cinux-iso
          path: cinux.iso
      
      - name: Create GitHub Release and Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$(date +"%m%d%y%H%M")" cinux.iso --title "Continuous release"
