name: Rebuild Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
     
      - name: Update package database
        run: sudo apt-get update

      - name: Install tools
        run: sudo apt-get install -y grub-pc-bin grub-common xorriso

      - name: Run build script
        run: ./build.sh

      - name: Create tag
        run: |
             git tag run-${{ github.run_number }}
             git push origin run-${{ github.run_number }}
     
      - name: Create new release
        run: |
             gh release create run-${{ github.run_number }} cdos.iso \
             --title "Continues Release" \
             --notes "Automated builds"
