name: Make Autogen Executable

on:
  workflow_dispatch:

jobs:
  chmod:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change permissions
        run: chmod +x autogen.sh

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add autogen.sh
          
          git commit -m "chore: make autogen.sh executable"
          git push
