# CINUX
# Copyright (C) 2025-2026 Connor Thomson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

name: Update ./configure

on:
  push:
    paths:
      - 'configure.ac'
      - 'Makefile.am'
      - '.github/workflows/update_configure.yaml'
    branches:
      - main

jobs:
  regenerate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Correct time
        run: |
          sudo timedatectl set-timezone America/Los_Angeles
          sudo timedatectl set-ntp true

      - name: Regenerate configure script
        run: autoreconf --install

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Makefile.in aclocal.m4 configure install-sh missing compile
          
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "chore: regenerate automake files"
            git push
          fi
