name: Update ./configure

on:
  push:
    paths:
      - 'configure.ac'
      - 'Makefile.am'
    branches:
      - main

jobs:
  regenerate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Regenerate configure script
        run: autoreconf --install --force

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Makefile.in aclocal.m4 configure install-sh missing
          
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "chore: regenerate automake files"
            git push
          fi
